# Generated by Django 3.2.2 on 2022-04-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='coin',
            new_name='coins',
        ),
    ]
